### ISSUE TITLE
login doesnt redirect to dash board

### ISSUE THREAD

**Issue by SkyBulk** [dimfu/poached#23]
I am trying to test your project; however, I cannot see any dashboard after the login. maybe my browser is cached or is this project a WIP

**Comment by dimfu** [comment]
I appreciate your efforts in testing my project. Just wanted to give you a heads up that the whole website is still in its early development stages. Gotta be honest, progress might be a tad slower than I hoped due to my crazy limited time availability 😅. But hey, no worries! I'm totally committed to making it better every day.
